### ISSUE TITLE
Feature Request: Text Customization Settings

### ISSUE THREAD

**Issue by JerryOrbachJr** [Taremin/webui-monaco-prompt#4]
Thank you for this nice extension. My request is for settings to control the style of the text, specifically the font size and the font family. In VS Code these are set via the editor.fontSize and editor.fontFamily parameters, and allow users to choose the font that is easiest for them to read.

**Comment by Taremin** [comment]
Thank you for your comment.
The font size change has already been implemented in 30ebe3d2a8f8879cffa11126b5932d4e5ce956d1 and will be included in the next release.
As for font families, unlike VSCode that runs locally, cannot get the list of installed fonts due to browser security reasons.
I can implement it if you want to choose a generic font family ( https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#generic-name ), but it's probably not what you want, right?

**Comment by JerryOrbachJr** [comment]
I think just the font size is more than enough! Thank you!

**Comment by Taremin** [comment]
I was mistaken,
VSCode also specified the font family directly instead of selecting from the list of installed fonts.
I will try to see if I can implement a UI for text input in Monaco.

**Comment by Taremin** [comment]
v0.1.6 was released with additional font size and font family settings.
Font families can be changed from the editor context menu.

**Comment by JerryOrbachJr** [comment]
Great work, thank you!
